services:
  - type: web
    name: colegio-bryce
    env: docker
    region: ohio
    plan: free
    envVars:
      - key: CI_ENVIRONMENT
        value: production
      - key: DEBUGBAR_ENABLED
        value: false
